config/routes.rb
Habitualize::Application.routes.draw do
  resources :flosses

  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
end

app/models/floss.rb
class Floss < ActiveRecord::Base
  attr_accessible :user, :skipped
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :provider, :uid, :name, :email, :first_name, :last_name, :image, :reminder, :next_reminder, :reminder_time, :next_session, :teacher_notes, :student_notes
  validates_presence_of :name

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
         user.first_name = auth['info']['first_name'] || ""
         user.last_name = auth['info']['last_name'] || ""
         user.image = auth['info']['image'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/flosses_controller.rb
class FlossesController < ApplicationController
  # GET /flosses
  # GET /flosses.json
  def index
    @flosses = Floss.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @flosses }
    end
  end

  # GET /flosses/1
  # GET /flosses/1.json
  def show
    @floss = Floss.find(params[:id])
    @user = User.where("id = ?", @floss.user).first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @floss }
    end
  end

  # GET /flosses/new
  # GET /flosses/new.json
  def new
    @floss = Floss.new
    @floss.user = current_user.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @floss }
    end
  end

  # GET /flosses/1/edit
  def edit
    @floss = Floss.find(params[:id])
  end

  # POST /flosses
  # POST /flosses.json
  def create
    @floss = Floss.new(params[:floss])

    respond_to do |format|
      if @floss.save
        format.html { redirect_to @floss}
        format.json { render json: @floss, status: :created, location: @floss }
      else
        format.html { render action: "new" }
        format.json { render json: @floss.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /flosses/1
  # PUT /flosses/1.json
  def update
    @floss = Floss.find(params[:id])

    respond_to do |format|
      if @floss.update_attributes(params[:floss])
        format.html { redirect_to @floss, notice: 'Floss was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @floss.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flosses/1
  # DELETE /flosses/1.json
  def destroy
    @floss = Floss.find(params[:id])
    @floss.destroy

    respond_to do |format|
      format.html { redirect_to flosses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    if current_user
    	@floss = Floss.new
    	@user = current_user
    	@floss.user = current_user.id
    	@my_flosses = Floss.where("user = ? and created_at < ?", current_user.id, Date.today)
    	@floss_today = Floss.where("user = ? and DATE(created_at) = ?", current_user.id, Date.today).last || 
    	@floss_yesterday = Floss.where("user = ? and DATE(created_at) = ?", current_user.id, Date.yesterday).last || 
    	@floss_three = Floss.where("user = ? and DATE(created_at) = ?", current_user.id, Date.today - 2.days).last ||
    	@floss_four = Floss.where("user = ? and DATE(created_at) = ?", current_user.id, Date.today - 3.days).last ||
    	@floss_five = Floss.where("user = ? and DATE(created_at) = ?", current_user.id, Date.today - 4.days).last ||
    	# decide to show the reminder
    	if (current_user.reminder_time != nil) and (Time.now > current_user.reminder_time) 
    		unless (@floss_today.created_at.today? if @floss_today)  or (Time.now < current_user.next_reminder)
    			@past_time = "reminder"
    		end
    	end
    end 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/facebook'
  end


  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'], 
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
# Reset the session after successful login, per
# 2.8 Session Fixation – Countermeasures:
# http://guides.rubyonrails.org/security.html#session-fixation-countermeasures
    reset_session
    session[:user_id] = user.id
    if user.email.blank?
      redirect_to edit_user_path(user), :alert => "Please enter your email address."
    else
      redirect_to root_url, :notice => 'Signed in!'
    end

  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])

  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to root_url
    else
      render :edit
    end
  end


def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flosses_helper.rb
module FlossesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/flosses/_form.html.erb
	<div class="row">
		<p class="sub-title">Hey <%= @user.first_name %>, how did it go?</p>
		<textarea name="comments" cols="25" rows="5" placeholder="Tell your teacher"></textarea>
	</div>
	<div class="row collapse">
	<!-- yes -->
	<div class="small-4 columns">
	<%= form_for(@floss) do |f| %>
	    <% #f.number_field :user %>
	    <%= f.hidden_field :user %>
	    <%= f.submit "Yes", :class=>"button popup" %>
	<% end %>
	</div>
	<!-- no -->
	<div class="small-4 columns">
	<%= form_for(@floss) do |n| %>
	  <%= n.hidden_field :user %>
	  <%= n.hidden_field :skipped, :value=>"1" %>
	  <%= n.submit "No", :class=>"button popup" %>
	<% end %>
	</div>

	<%= form_for(@user) do |g| %>
	<div class="small-4 columns">
	  <%= g.submit "Snooze", :class=>"button popup-snooze" %>
	</div>
	<% end %>
</div>

<!-- snooze -->
<!--
<div class="row">
	<%= form_for(@user) do |g| %>
	
	<div class="small-6 columns">
	  <%= g.select(:next_reminder, options_for_select([['1 hour', Time.now.to_datetime+1.hours], ['2 hours', Time.now.to_datetime+2.hours], ['3 hours', Time.now.to_datetime+3.hours], ['4 hours', Time.now.to_datetime+4.hours]])) %>
	  <br />
	</div>
	
	<div class="small-6 columns">
	  <%= g.submit "Snooze :-/", :class=>"button popup" %>
	</div>
	<% end %>
</div>
-->

app/views/flosses/edit.html.erb
<h1>Editing floss</h1>

<%= render 'form' %>

<%= link_to 'Show', @floss %> |
<%= link_to 'Back', flosses_path %>

app/views/flosses/index.html.erb
<h1>Listing flosses</h1>

<table>
  <tr>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @flosses.each do |floss| %>
  <tr>
    <td><%= floss.user %></td>
    <td><%= link_to 'Show', floss %></td>
    <td><%= link_to 'Edit', edit_floss_path(floss) %></td>
    <td><%= link_to 'Destroy', floss, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Floss', new_floss_path %>

app/views/flosses/new.html.erb
<h1>New floss</h1>

<%= render 'form' %>

<%= link_to 'Back', root_url %>

app/views/flosses/show.html.erb
<% if @floss.skipped == 1 %>
<p>
Really? You aren't going to floss??
</p>

<% else %>
<div class="hero">
  <div class="row">
    <div class="large-12 small-12 columns">
    	<p class="center"><%= image_tag "drummaster.png", :class=>"star" %></center>
    </div>
  </div>
<div class="row">
	<div class="large-12 small-12 end scolumns">
      <p class="success-text center">Great work <%= @user.first_name %>!</p>
      <p class="center share">Show off:
      <a href="#" class="zocial facebook" style="font-size:10px;">post</a> <a href="#" class="zocial twitter" style="font-size:10px;">tweet</a></br>
      <p class="center"><%= link_to 'Back', root_path, :class=>"button popup-snooze" %></p>
  </p>
    </div>
</div>
</div>
<% end %>


<div class="row">
	<div class="large-12 small-12 columns">
		<p class="title-dark">Leaderboard</p>
	</div>
</div>

<% User.all.each do |user| %>
  <div class="row status">
    <div class="large-3 small-3 columns">
      <%= image_tag user.image, :class=>"pic-small" %>
    </div>
    <div class="large-6 small-6 columns">
      <p class="status-text"><%= user.name %></p>
    </div>
    <div class="large-3 small-3 columns">
      <p class="status-text"><%= Floss.where('user = ?', user.id).count %></p>
    </div>
  </div>
  <% end %>

app/views/home/_logged_in.html.erb
<div class="hero">
  <div class="row">
    <div class="large-2 small-4 columns">
    	<%= image_tag current_user.image %>
    </div>
    <div class="large-6 small-8 end scolumns">
      <p class="name"><%= current_user.name %></p>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
        <p class="instructions">
          <b>Teacher Notes</b><br />
          10 minutes: Warmup<br />
          5 minutes: Paradiddles<br />
          5 minutes: Triple stroke rolls<br />
          5 minutes: Single flammed mill<br />
          5 minutes: Inverted flam tap<br />
          10 minutes: Play along with Track 12<br />
      </p>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <p class="center"><a href="#" data-reveal-id="myModal" class="button checkin">Did you practice?</a></p>
    </div>
  </div>
</div>
  <br />

<!-- today -->
<% if @floss_today %>
<% if @floss_today.skipped %>
  <div class="row status">
    <div class="large-3 small-3 columns">
      <img src="assets/x.png">
    </div>
    <div class="large-9 small-9 columns">
      <p class="status-text">You skipped today</p>
      <p class="sub-status-text">Come on! You can do it.</p>
    </div>
  </div>
<% else %>
  <div class="row status">
    <div class="large-3 small-3 columns">
      <img src="assets/check.png">
    </div>
    <div class="large-9 small-9 columns">
      <p class="status-text">You practiced today! Go you!</p>
      <p class="sub-status-text">Done at <%= @floss_today.created_at.to_s(:reminder_time) %>!</p>
    </div>
  </div>
<% end %>
<% else %>
<div class="row status">
    <div class="large-3 small-3 columns">
      <img src="assets/alarm.png">
    </div>
    <div class="large-9 small-9 columns">
      <p class="status-text">You practiced today</p>
      <p class="sub-status-text">You haven't practiced yet. There's still time!</p>
    </div>
  </div>
<% end %>




<!-- yesterday -->
<% if @floss_yesterday %>
<% if @floss_yesterday.skipped %>
  <div class="row status">
    <div class="large-3 small-3 columns">
      <img src="assets/x.png">
    </div>
    <div class="large-9 small-9 columns">
      <p class="status-text">You skipped yesterday.</p>
      <p class="sub-status-text">Just take it one day at a time.</p>
    </div>
  </div>
<% else %>
  <div class="row status">
    <div class="large-3 small-3 columns">
      <img src="assets/check.png">
    </div>
    <div class="large-9 small-9 columns">
      <p class="status-text">You practiced yesterday! Great job!</p>
      <p class="sub-status-text">Done at <%= @floss_yesterday.created_at.to_s(:reminder_time) %>!</p>
    </div>
  </div>
<% end %>
<% else %>
<div class="row status">
    <div class="large-3 small-3 columns">
      <img src="assets/x.png">
    </div>
    <div class="large-9 small-9 columns">
      <p class="status-text">You skipped yesterday.</p>
      <p class="sub-status-text">Just take it one day at a time.</p>
    </div>
  </div>
<% end %>

<!-- 2 days ago -->
<% if @floss_three %>
<% if @floss_three.skipped %>
  <div class="row status">
    <div class="large-3 small-3 columns">
      <img src="assets/x.png">
    </div>
    <div class="large-9 small-9 columns">
      <p class="status-text">You didn't practice on <%= (Date.today-2.days).strftime("%A") %>.</p>
      <p class="sub-status-text">Aw, you can always practice today.</p>
    </div>
  </div>
<% else %>
  <div class="row status">
    <div class="large-3 small-3 columns">
      <img src="assets/check.png">
    </div>
    <div class="large-9 small-9 columns">
      <p class="status-text">You practiced yesterday! Keep it up!</p>
      <p class="sub-status-text">Done at <%= @floss_three.created_at.to_s(:reminder_time) %>!</p>
    </div>
  </div>
<% end %>
<% else %>
<div class="row status">
    <div class="large-3 small-3 columns">
      <img src="assets/x.png">
    </div>
    <div class="large-9 small-9 columns">
      <p class="status-text">You didn't practice on <%= (Date.today-2.days).strftime("%A") %>.</p>
      <p class="sub-status-text">Aw, you can always practice today.</p>
    </div>
  </div>
<% end %>

<!-- 3 days ago -->
<% if @floss_four %>
<% if @floss_four.skipped %>
  <div class="row status">
    <div class="large-3 small-3 columns">
      <img src="assets/x.png">
    </div>
    <div class="large-9 small-9 columns">
      <p class="status-text">You didn't practice on <%= (Date.today-3.days).strftime("%A") %>.</p>
      <p class="sub-status-text">Is it really that hard?</p>
    </div>
  </div>
<% else %>
  <div class="row status">
    <div class="large-3 small-3 columns">
      <img src="assets/check.png">
    </div>
    <div class="large-9 small-9 columns">
      <p class="status-text">You practiced yesterday! Awesome job!</p>
      <p class="sub-status-text">Done at <%= @floss_four.created_at.to_s(:reminder_time) %>!</p>
    </div>
  </div>
<% end %>
<% else %>
<div class="row status">
    <div class="large-3 small-3 columns">
      <img src="assets/x.png">
    </div>
    <div class="large-9 small-9 columns">
      <p class="status-text">You didn't practice on <%= (Date.today-3.days).strftime("%A") %>.</p>
      <p class="sub-status-text">Is it really that hard?</p>
    </div>
  </div>
<% end %>


<!-- 4 days ago -->
<% if @floss_five %>
<% if @floss_five.skipped %>
  <div class="row status">
    <div class="large-3 small-3 columns">
      <img src="assets/x.png">
    </div>
    <div class="large-9 small-9 columns">
      <p class="status-text">You didn't practice on <%= (Date.today-4.days).strftime("%A") %>.</p>
      <p class="sub-status-text">You can change!</p>
    </div>
  </div>
<% else %>
  <div class="row status">
    <div class="large-3 small-3 columns">
      <img src="assets/check.png">
    </div>
    <div class="large-9 small-9 columns">
      <p class="status-text">You practiced yesterday! You're awesome!</p>
      <p class="sub-status-text">Done at <%= @floss_five.created_at.to_s(:reminder_time) %>!</p>
    </div>
  </div>
<% end %>
<% else %>
<div class="row status">
    <div class="large-3 small-3 columns">
      <img src="assets/x.png">
    </div>
    <div class="large-9 small-9 columns">
      <p class="status-text">You didn't practice on <%= (Date.today-4.days).strftime("%A") %>.</p>
      <p class="sub-status-text">You can change!</p>
    </div>
  </div>
<% end %>
  

    </div>
  </div>


<!-- show the popup if it's your time to floss! -->
<% if @past_time %>
	<script type="text/javascript">
//	$(document).ready(function() {
//    $("#myModal").foundation('reveal', 'open');
//	});
	</script>
<% end %>


<!-- modal ux: find the rest in flosses/form -->
<div id="myModal" class="reveal-modal">
  <p class="title">Did you practice?</p>
  <%= render "flosses/form"  %>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/home/_logged_out.html.erb
you're logged out! this is in /views/home/logged_out

app/views/home/index.html.erb
<% if current_user %>
	<%= render 'logged_in' %>
<% else %>
	<%= render 'logged_out' %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
  <nav class="top-bar">
    <ul class="title-area">
      <!-- Title Area -->
      <li class="name">
        <h1>
          <a href="<%= root_path %>">
            <%= image_tag 'Habit43.png' %>
          </a>
        </h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
    </ul>
 
    <% if user_signed_in? %>

     <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <li><a href="#"><%= current_user.name %></a></li>
        <li><%= link_to "Admin", users_path %></li>
        <li><a href="<%= signout_path %>">Logout</a></li>
      </ul>
    </section>

    <% else %>
      <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
          <a href="<%= signin_path %>">Login</a>
      </ul>
    </section>

    <% end %>

  </nav>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Habitualize" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Habitualize" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "zocial", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <meta name="apple-mobile-web-app-capable" content="yes" /> 
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta content="minimum-scale=1.0, width=device-width, maximum-scale=0.6667, user-scalable=no" name="viewport" />
    <link rel="apple-touch-icon" href="/assets/habit h logo.jpg" />
    <link rel="icon" type="image/png" href="/assets/16.png" />
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div id="container" class="container">
      <header>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
      </header>
      <div id="main" role="main">
        <%= yield %>
      </div>
      <footer>
      </footer>
    </div> <!--! end of #container -->

<script type="text/javascript">
  window.addEventListener("load",function() {
    // Set a timeout...
    setTimeout(function(){
      // Hide the address bar!
      window.scrollTo(0, 1);
    }, 0);
  });
</script>

  </body>
</html>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
	<%= image_tag @user.image %><%= @user.name %>
	</br>

<%= f.label "#{@user.first_name}'s Comments from this week:" %>
<em>I think I'm finally getting track 12. Maybe it's time for a new one?</em>
</br>

<%= f.label "Notes for this week" %>
 <%= f.text_field :teacher_notes, :rows=>"3" %>

<%= f.label "Next session" %>
 <%= f.time_select :next_session %>
	
  <%= f.label "Daily reminder time" %>
  <%= f.time_select :reminder_time %>

  <br />
  <%= f.submit "Save" %>
<% end %>

app/views/users/index.html.erb
<div class="row hero">
	<div class="large-12 small-12 columns">
		<p class="page-title">Jason's Music School</p>
	</div>
</div>



<div class="row status">
	<div class="large-3 small-6 end columns">
	  <p class="title-dark">
	  	Students
	  </p>
	</div>
</div>
<% @users.each do |user| %>
<div class="row status">
	<div class="large-3 small-3 columns">
	  <p class="status-text">
	  	<%= image_tag user.image, :class=>"pic-small" %>
	  </p>
	</div>
	<div class="large-5 small-5 columns">
	  <p class="status-text">
	  	<%= link_to user.name, edit_user_path(user) %>
	  </p>
	</div>
	<div class="large-4 small-4 columns">
	  <p class="status-text">
		<%= user.next_session.to_date if user.next_session %>
	  </p>
	</div>
</div>
<% end %>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<p>Reminder time: <%= @user.reminder_time.to_s(:reminder_time) %></p>